In [9]:
import pandas as pd
import numpy as np
import os

In [10]:
cwd = os.getcwd()
#probs = pd.read_csv("./HomelessnessProbs.csv")

In [11]:
cwd

'/home/ltmico/Hack'

In [13]:
df.to_csv('./example.csv')
file_old = './example.csv'

In [37]:
#Names for the files to use as probalities
file = './PIT_2015 - POCvsGeneral.csv'

In [38]:
#Check I've got it right
file

'./PIT_2015 - POCvsGeneral.csv'

In [39]:
#read the csv
probs = pd.read_csv(file)

In [40]:
#look at it
probs

,populationType,year,individual,familiesWChild,SNAP,chronicallyHomeless,disablingCond,veteran,domesticViolencef,female,male,youth,unk,MultTotalProp,Portland,Homeless,unsheltered,emergencyShelter,transitionalHousing,page
0,White,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.826,0.741,0.67,NaN,NaN,NaN,12.0
1,NonWhite,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.174,0.259,0.33,NaN,NaN,NaN,NaN
2,NPOC,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.622,0.592,0.58,NaN,NaN,NaN,12.0
3,POC,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.378,0.408,0.42,NaN,NaN,NaN,12.0
4,White,11.0,NaN,0.06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.810,NaN,0.67,0.76,0.71,0.57,27.0
5,NonWhite,11.0,NaN,0.94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.190,NaN,0.33,0.24,0.29,0.43,NaN
6,NPOC,11.0,NaN,0.46,NaN,NaN,NaN,NaN,NaN,0.37,0.62,NaN,0.01,0.710,NaN,0.54,0.66,0.58,0.42,24.0
7,POC,11.0,NaN,0.54,NaN,0.25,NaN,0.10,0.22,0.40,0.58,NaN,0.02,0.290,NaN,0.46,0.34,0.42,0.58,26.0
8,totalhmlss,11.0,NaN,0.29,NaN,0.29,NaN,0.12,0.18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,White,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.810,NaN,0.69,0.75,0.61,0.67,29.0
10,NonWhite,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.190,NaN,0.31,0.25,0.39,0.33,NaN
11,NPOC,13.0,0.43,0.58,0.32,NaN,0.57,0.92,0.57,0.58,0.42,0.99,0.99,0.710,NaN,0.55,0.62,0.49,0.49,33.0
12,POC,13.0,0.57,0.42,0.68,NaN,0.43,0.08,0.43,0.42,0.58,0.01,0.01,0.290,NaN,0.45,0.38,0.51,0.51,NaN
13,totalhmlss,13.0,0.71,0.28,0.28,NaN,0.53,0.11,0.41,0.38,0.61,0.01,0.02,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,White,15.0,0.17,0.17,0.66,NaN,NaN,NaN,0.26,NaN,NaN,NaN,NaN,0.820,NaN,0.73,1.00,0.66,0.77,15.0
15,NonWhite,15.0,0.83,0.83,0.34,NaN,NaN,NaN,0.74,NaN,NaN,NaN,NaN,0.180,NaN,0.27,0.26,0.34,0.23,NaN
16,NPOC,15.0,0.26,0.17,0.72,NaN,NaN,NaN,0.56,0.60,0.40,0.99,0.99,0.700,NaN,0.59,0.61,0.51,0.62,57.0
17,POC,15.0,0.74,0.26,0.28,NaN,0.51,0.12,0.44,0.40,0.60,0.01,0.01,0.300,NaN,0.41,0.39,0.49,0.38,14.0
18,totalhmlss,15.0,0.83,0.17,NaN,NaN,0.57,0.10,0.45,0.36,0.64,0.01,0.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,unk,NaN,NaN,NaN,0.06,NaN,0.42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39.0
20,NOTES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [53]:
df = pd.DataFrame(probs)

In [54]:
##subset only 2015 to make it moe manageable
df = df[df.year == 15.0]
df

,populationType,year,individual,familiesWChild,SNAP,chronicallyHomeless,disablingCond,veteran,domesticViolencef,female,male,youth,unk,MultTotalProp,Portland,Homeless,unsheltered,emergencyShelter,transitionalHousing,page
14,White,15.0,0.17,0.17,0.66,NaN,NaN,NaN,0.26,NaN,NaN,NaN,NaN,0.82,NaN,0.73,1.00,0.66,0.77,15.0
15,NonWhite,15.0,0.83,0.83,0.34,NaN,NaN,NaN,0.74,NaN,NaN,NaN,NaN,0.18,NaN,0.27,0.26,0.34,0.23,NaN
16,NPOC,15.0,0.26,0.17,0.72,NaN,NaN,NaN,0.56,0.60,0.40,0.99,0.99,0.70,NaN,0.59,0.61,0.51,0.62,57.0
17,POC,15.0,0.74,0.26,0.28,NaN,0.51,0.12,0.44,0.40,0.60,0.01,0.01,0.30,NaN,0.41,0.39,0.49,0.38,14.0
18,totalhmlss,15.0,0.83,0.17,NaN,NaN,0.57,0.10,0.45,0.36,0.64,0.01,0.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [66]:
poc_prob = dict(df.iloc[3])
poc_prob

{'Homeless': 0.40999999999999998,
 'MultTotalProp': 0.29999999999999999,
 'Portland': nan,
 'SNAP': 0.28000000000000003,
 'chronicallyHomeless': nan,
 'disablingCond': 0.51000000000000001,
 'domesticViolencef': 0.44,
 'emergencyShelter': 0.48999999999999999,
 'familiesWChild': 0.26000000000000001,
 'female': 0.40000000000000002,
 'individual': 0.73999999999999999,
 'male': 0.59999999999999998,
 'page': 14.0,
 'populationType': 'POC',
 'transitionalHousing': 0.38,
 'unk': 0.01,
 'unsheltered': 0.39000000000000001,
 'veteran': 0.12,
 'year': 15.0,
 'youth': 0.01}

In [94]:
metsPOC = ['Homeless', 'male','veteran','disablingCond']
probs = [poc_prob[metsPOC[0]], poc_prob[metsPOC[1]],poc_prob[metsPOC[2]],poc_prob[metsPOC[3]]]
#test = [poc_prob['Homeless']
probs
#probs = poc_prob['individual']

[0.40999999999999998, 0.59999999999999998, 0.12, 0.51000000000000001]

Ok now that I have the probabilities read in I want to start simulating a dataset

In [97]:
##lets start the sim
import random

## set the seed
random.seed = 1978

#dat = [] #empty list to store the values for one person

output = []
for i in range(1,3802) : # sim 3801 individuals
    dat = [] #empty list to store the values for one person
    
    ##defines if you are POC, male, vet, or disabled
    for p in probs :
        #print(p)
        if random.random() < p:
            temp = 1 #yes
        else:
            temp = 0 #no
            #print(temp)
        dat.append(temp)
    
    ##defines if you are 
    if 
        
        
        
        
        
        
    output.append(dat) #adds the new 'individual' values to the list

In [99]:
colnames = ['poc', 'male','veteran','disability']
simdat = pd.DataFrame(output,columns=colnames) 
simdat.head()

   poc  male  veteran  disability
0    1     1        0           0
1    1     1        0           1
2    0     1        0           1
3    0     0        0           0
4    0     0        0           0

In [108]:
##Define a function to calculate the marginal probalities
margins = simdat.sum(axis=0)/3801
margins

poc           0.404893
male          0.585372
veteran       0.114707
disability    0.499868
dtype: float64

In [105]:
probs

[0.40999999999999998, 0.59999999999999998, 0.12, 0.51000000000000001]

In [109]:
##The difference between the margins of the simulated dataset and the desired margins
probs - margins

poc           0.005107
male          0.014628
veteran       0.005293
disability    0.010132
dtype: float64